### ISSUE TITLE
serial port

### ISSUE THREAD

**Issue by liadhazoot5** [net-guy/citaq#2]
Hey :)
I try to use the application and run it on a device. but I saw that there is no Gradle File here
how can i run the application?

**Comment by net-guy** [comment]
Hello there @liadhazoot5,

To be honest with you mate, it's been a while since I've actually gone back to this project, I really only uploaded it all to github to consolidate and share the info.

I haven't played with the SDK yet or made a successful connection to the serial port on the printer, sorry mate, I'm not a lot of help.

There's not much in this repo, but I really think this is a cool project. If you find/learn anything that could be useful for others, please fork the repo and make a pull request, keep this alive, it's a nifty little device.

~ NetGuy

**Comment by net-guy** [comment]
Marking as closed due to no user response.
